### ISSUE TITLE
You can try yarn create command :)

### ISSUE THREAD

**Issue by torifat** [jchappypig/react-workshop#1]
```shell
$ yarn create react-app <my-app>
```

https://yarnpkg.com/lang/en/docs/cli/create/#toc-yarn-create

**Comment by jchappypig** [comment]
Nice~ thank you!

On 30 May 2018, at 11:44 pm, Rifat Nabi <notifications@github.com<mailto:notifications@github.com>> wrote:


$ yarn create react-app <my-app>

https://yarnpkg.com/lang/en/docs/cli/create/#toc-yarn-create
